//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShopesms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedures
    {
        public long ID { get; set; }
        public string Procedure_type { get; set; }
        public long InvoiceNo { get; set; }
        public decimal Ammount { get; set; }
        public long User_Id { get; set; }
        public string User_Name { get; set; }
        public System.DateTime ddate { get; set; }
        public long ShopId { get; set; }
    }
}
