//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShopesms
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInvoice
    {
        public long ID { get; set; }
        public long InvoiceNo { get; set; }
        public long MatiralBarcode { get; set; }
        public string MatiralName { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Total_ { get; set; }
        public decimal Profit_One_Item { get; set; }
        public Nullable<decimal> Total_Profits { get; set; }
        public System.DateTime Ddate { get; set; }
        public long User_ID { get; set; }
        public string UserName { get; set; }
        public int Shopid { get; set; }
        public int CashOrCredit { get; set; }
    }
}
