//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShopesms
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesView
    {
        public long MatiralBarcode { get; set; }
        public string MatiralName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public int Shopid { get; set; }
    }
}
