//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShopesms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public long User_ID { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public int ShopId { get; set; }
        public string ShopName { get; set; }
    }
}
