//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShopesms
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAllBalance
    {
        public long MatirialBarcode { get; set; }
        public string MatirialName { get; set; }
        public decimal Pricein { get; set; }
        public int Shopid { get; set; }
        public Nullable<decimal> BuingQuantity { get; set; }
        public Nullable<decimal> SalesQuantity { get; set; }
        public Nullable<decimal> TotalOfQuantity { get; set; }
        public Nullable<decimal> Balanco { get; set; }
    }
}
